framework:
  test: true
  session:
    storage_factory_id: session.storage.factory.mock_file

services:
  _defaults:
    autoconfigure: true
    autowire: true

  AdrianDev374\Tests\:
    resource: '../../../tests'
